wandb_version: 1

ARCHITECTURE:
  value: single-layer-perceptron
BATCH_SIZE:
  value: 16
DATASET:
  value: MNIST-handwrite
DATA_PATH:
  value: ../dataset/
EPOCHS:
  value: 10
LEARNING_RATE:
  value: 0.003952212645477704
NOW:
  value: '2021-09-20T23:08:40'
NUM_WORKERS:
  value: 1
SAVEFIG_NAME:
  value: result.png
