wandb_version: 1

ARCHITECTURE:
  desc: null
  value: single-layer-perceptron
BATCH_SIZE:
  desc: null
  value: 16
DATASET:
  desc: null
  value: MNIST-handwrite
DATA_PATH:
  desc: null
  value: ../dataset/
EPOCHS:
  desc: null
  value: 10
LEARNING_RATE:
  desc: null
  value: 0.0494966499609768
NOW:
  desc: null
  value: '2021-09-20T23:08:40'
NUM_WORKERS:
  desc: null
  value: 1
SAVEFIG_NAME:
  desc: null
  value: result.png
_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.6.9
    start_time: 1632146974
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.6.9
      5: 0.12.1
      8:
      - 2
      - 5
