wandb_version: 1

ARCHITECTURE:
  value: single-layer-perceptron
BATCH_SIZE:
  value: 16
DATASET:
  value: MNIST-handwrite
DATA_PATH:
  value: ../dataset/
EPOCHS:
  value: 10
LEARNING_RATE:
  value: 0.0045372429021101075
NOW:
  value: None
NUM_WORKERS:
  value: 1
SAVEFIG_NAME:
  value: result.png
