wandb_version: 1

NOW:
  desc: null
  value: '2021-09-20T23:02:56'
SAVEFIG_NAME:
  desc: null
  value: result.png
_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.6.9
    start_time: 1632146585
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.6.9
      5: 0.12.1
      8:
      - 2
      - 5
batchsize:
  desc: null
  value: 64
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.05760312348262441
name:
  desc: null
  value: sweep-2021-09-20T23:03:06
