wandb_version: 1

ARCHITECTURE:
  value: single-layer-perceptron
DATASET:
  value: MNIST-handwrite
DATA_PATH:
  value: ../dataset/
NOW:
  value: '2021-09-20T23:05:08'
SAVEFIG_NAME:
  value: result.png
batchsize:
  value: 32
epochs:
  value: 10
learning_rate:
  value: 0.045460396535371206
