name: Coverage Report

on: push

jobs:
  coverage-report:
    name: Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Generate coverage report
        run: |
          # descover and run the all coverage files under this directory 
          coverage run --source=./ -m unittest discover -p "*_test.py"
          coverage xml
      
      - name: Upload coverage report to code climate
        uses : paambaati/codeclimate-action@v2.7.5
        env :
          CC_TEST_REPORTER_ID: 1b297159a739e9797dffddb582855c0c8d239939cad5bcfdb2a1271a0a1e8a31